home:
  path: /
  controller: App\Controller\CatalogController::index

show:
  path: /show/{id}
  controller: App\Controller\CatalogController::show

listProducts:
  path: /list
  controller: App\Controller\CartController::listProducts

deleteSession:
  path: /deleteSession
  controller: App\Controller\CartController::deleteSession