home:
  path: /
  controller: App\Controller\CatalogController::index

show:
  path: /show/{id}
  controller: App\Controller\CatalogController::show

add:
  path: /add
  controller: App\Controller\CatalogController::add

listProducts:
  path: /list
  controller: App\Controller\CartController::listProducts

deleteSession:
  path: /deleteSession
  controller: App\Controller\CartController::deleteSession

calculPrice:
  path: /calculPrice/{typeCalculPrice}
  controller: App\Controller\CartController::calculPrice